/**
 * Shopify — ongoing development, retainers and hourly work. The other half of
 * the old combined page; new store builds live on /shopify-development-services.
 */
import type { ServicePageData } from "./types";
import {
  SHOPIFY_CLIENT_LOGOS,
  SHOPIFY_CLOSING_NOTE,
  SHOPIFY_COMMON_FAQ,
  SHOPIFY_WHY_US,
} from "./shopify-shared";

export const shopifyDeveloper: ServicePageData = {
  hero: {
    variant: "showcase",
    heading: "Hire a Shopify Developer",
    subheading: "A developer on call for your live store.",
    intro:
      "Your store is live but you need a reliable developer for updates, fixes, new features, and design changes. No more chasing freelancers. Pay hourly for one-off jobs or take a monthly retainer — no lock in.",
    partnerLogo: {
      src: "/assets/images/shopify-partners.webp",
      alt: "Shopify Partners",
    },
    badges: [
      "Registered Shopify Partner",
      "Pay monthly or hourly, no lock in",
      "Priority response within 24hrs",
      "Dedicated developer who knows your store",
      "Deal direct, no managers",
    ],
    ctaPrimary: { label: "Hourly Pricing", href: "#hourly-pricing" },
    ctaSecondary: { label: "Schedule free strategy Call", href: "/schedule-strategy-call" },
    heroImage: "/assets/images/WRjXIBfZxMI8DrDHJoRoBdiFgds.webp",
  },
  blocks: [
    SHOPIFY_CLIENT_LOGOS,
    { type: "testimonials" },
    {
      type: "cardgrid",
      theme: "paper",
      kicker: "Services Section",
      eyebrow: "Rankify®",
      anchorId: "services",
      heading: "What we handle on your live store",
      subheading:
        "Bug fixes, design changes, new features, integrations and audits — handled by a developer who already knows your setup.",
      cta: { label: "Hourly Packages", href: "#hourly-pricing" },
      columns: 4,
      items: [
        { idx: "01", anchorId: "customisation-requests", title: "Shopify Customisation Requests", desc: "Already have a Shopify store? We customise existing themes — section layouts, custom Liquid code, design tweaks, and functionality improvements. Get the store you want without starting from zero." },
        { idx: "02", anchorId: "ongoing-support", title: "Ongoing Shopify Support & Maintenance", desc: "Retainer-based support for businesses that need a reliable Shopify developer on call. Bug fixes, design updates, new features, product uploads, third-party app troubleshooting, and performance monitoring — all covered under a monthly plan." },
        { idx: "03", anchorId: "app-integrations", title: "Shopify App & Third-Party Integrations", desc: "We integrate apps for email marketing (Klaviyo, Mailchimp), reviews (Judge.me, Loox), subscriptions (Recharge), shipping (Sendle, Australia Post), accounting (Xero, MYOB), and more. We recommend what you actually need — not every app in the store." },
        { idx: "04", anchorId: "store-audits", title: "Shopify Store Audits", desc: "Existing store underperforming? We audit your Shopify store for speed, UX, SEO, conversion blockers, and technical issues — then give you a prioritised action plan to fix what matters most." },
      ],
    },
    {
      type: "pricing",
      anchorId: "hourly-pricing",
      eyebrow: "Retainer & Hourly Pricing",
      heading: "Retainer & Hourly Pricing",
      subheading: "Most agencies charge $350–$500/hr for Shopify development. We offer dedicated retainer support from $499/month.",
      lookingForMore: true,
      lookingForMoreCta: { label: "Book a call", href: "/schedule-strategy-call" },
      tiers: [
        {
          name: "Casual",
          spots: "8 Spots Available",
          price: "$275",
          period: "/ hourly",
          note: "On-demand Shopify development for one-off jobs. Pay per hour, no commitment.",
          features: [
            "Bug fixes",
            "Design or content changes",
            "Troubleshooting",
            "Content updates",
            "Product and collection uploads",
            "App installs and configuration",
            "Custom Liquid code edits",
            "SEO and metadata updates",
          ],
          ctaLabel: "Order Now",
          ctaHref: "/contact",
        },
        {
          name: "Growth",
          spots: "8 Spots Available",
          price: "$499",
          period: "/ monthly",
          note: "2 hours of dedicated Shopify development each month for your custom requests. No lock in.",
          features: [
            "Overflow hours $249/hr",
            "Priority response (within 24hrs)",
            "Priority in job queue",
            "Summary of work completed",
            "Dedicated developer who knows your store",
            "Bug fixes, content updates & troubleshooting",
            "Product and collection uploads",
            "App installs and configuration",
          ],
          ctaLabel: "Order Now",
          ctaHref: "/contact",
        },
        {
          name: "Scale",
          badge: "MOST POPULAR",
          highlighted: true,
          spots: "8 Spots Available",
          price: "$999",
          period: "/ monthly",
          note: "5 hours of dedicated Shopify development each month for your custom requests. No lock in.",
          features: [
            "Overflow hours $199/hr",
            "Priority response (within 24hrs)",
            "Priority in job queue",
            "Summary of work completed",
            "Dedicated developer who knows your store",
            "Bug fixes, content updates & troubleshooting",
            "Product and collection uploads",
            "App installs and configuration",
          ],
          ctaLabel: "Order Now",
          ctaHref: "/contact",
        },
      ],
    },
    {
      type: "cardgrid",
      theme: "paper",
      kicker: "Hourly & Retainer Work",
      eyebrow: "Rankify®",
      anchorId: "how-it-works",
      heading: "How does it work? A simple process",
      cta: { label: "Hourly Packages", href: "#hourly-pricing" },
      columns: 2,
      items: [
        { idx: "01", title: "Place your order or book a call", image: "/assets/images/Z6tHt1zj6Xzi4mqYcUDecqw9s.png", desc: "Choose a package or chat with us if you want to ask a few questions first." },
        { idx: "02", title: "Submit your request", image: "/assets/images/ZZc0y2OxRuZ9xbEv3CFdHDFMw.webp", desc: "Send through what you need — bug fixes, design changes, new features, content updates. We'll confirm scope and give you a time estimate." },
        { idx: "03", title: "We get to work", image: "/assets/images/OcCBB2O75VsaHiIw8nfSpLAtJjo.webp", desc: "Your developer picks it up and gets it done. No project managers, no back-and-forth. Direct communication the whole way." },
        { idx: "04", title: "Review & approve", image: "/assets/images/8TLWcrZrVHY4Nwhm6KhqsAbL9A.webp", desc: "We walk you through the changes on your live or staging site. Not happy? We adjust until it's right." },
      ],
    },
    SHOPIFY_WHY_US,
    {
      type: "cardgrid",
      theme: "paper",
      kicker: "Need a new store instead?",
      eyebrow: "Rankify®",
      anchorId: "new-store",
      heading: "Starting from scratch, or moving to Shopify?",
      subheading:
        "Ongoing work is for stores that are already live. If you need a store designed and built from the ground up, that's a separate service with its own fixed-quote process.",
      cta: { label: "See new store builds", href: "/shopify-development-services" },
      columns: 3,
      items: [
        { idx: "01", title: "Launching a new store", desc: "You need a custom Shopify store built properly from day one. Design, development, products, payments, shipping, and SEO — all handled.", cta: { label: "New store builds", href: "/shopify-development-services" } },
        { idx: "02", title: "Migrating to Shopify", desc: "You're on WooCommerce, Squarespace, Magento, or an outdated platform and need a clean migration to Shopify without losing your search rankings or customer data.", cta: { label: "Migration details", href: "/shopify-development-services#shopify-migration" } },
        { idx: "03", title: "Scaling & Shopify Plus", desc: "You've outgrown standard Shopify and need custom checkout, B2B functionality, or advanced integrations. We work with Shopify Plus for stores that need enterprise-level features.", cta: { label: "Shopify Plus", href: "/shopify-development-services#scaling-shopify-plus" } },
      ],
    },
  ],
  faq: {
    heading: "FAQ.",
    subheading: "Got questions? We've got answers. Here's everything you need to know about working with us.",
    closingNote: SHOPIFY_CLOSING_NOTE,
    items: [
      { q: "What does your ongoing Shopify support retainer include?", a: "Our retainer plans start at $249/month for 2 hours and cover bug fixes, design updates, content changes, new features, app troubleshooting, and performance monitoring. You get a dedicated developer who already knows your store — no re-explaining your setup every time. Overflow hours are billed at $125/hr." },
      { q: "Can you integrate third-party apps with my Shopify store?", a: "Yes. We integrate with Klaviyo, Mailchimp, Judge.me, Loox, Recharge, Sendle, Australia Post, Xero, MYOB, and more. We recommend apps based on what your business actually needs rather than loading your store with unnecessary tools." },
      { q: "Do I have to sign a lock-in contract?", a: "No. Retainers are month to month and hourly work is on demand — pay per hour for one-off jobs with no commitment." },
      { q: "Can you work on a store you didn't build?", a: "Yes. Most of our retainer clients came to us with an existing store. We customise existing themes — section layouts, custom Liquid code, design tweaks, and functionality improvements — without starting from zero." },
      { q: "Do you work with Shopify Plus?", a: "Yes. We build on Shopify Plus for businesses that need advanced features — custom checkout, B2B wholesale portals, multi-currency, and advanced API integrations. We'll advise whether standard Shopify or Shopify Plus is the right fit based on your requirements and sales volume." },
      ...SHOPIFY_COMMON_FAQ,
    ],
  },
};
